#pragma once

#include "ECS/Components/Animation2DComponent.h"
#include "ECS/Components/AudioSourceComponent.h"
#include "ECS/Components/BehaviourComponent.h"
#include "ECS/Components/Rigidbody2DComponent.h"
#include "ECS/Components/CameraComponent.h"
#include "ECS/Components/CanvasComponent.h"
#include "ECS/Components/HeadComponent.h"
#include "ECS/Components/Light2DSourceComponent.h"
#include "ECS/Components/Texture2DComponent.h"
#include "ECS/Components/TransformComponent.h"
#include "ECS/Components/MeshComponent.h"
#include "ECS/Components/SpotLightComponent.h"
#include "ECS/Components/PointLightComponent.h"
#include "ECS/Components/SceneStateComponent.h"
#include "ECS/Components/RigidbodyComponent.h"